include(":tvapp")
include(":GenreList")
include(":ViewComponents")
include(":UiBase")
include(":AndroidBase")
include(":DaggerCore")
include(":mainpagetv")
include(":Remote")
include(":Local")
include(":Domain")
include(":Data")
include(":Favorite")
include(":Search")
include(":MainPage")
include(":app")
rootProject.name = "Movotlin"
rootProject.buildFileName = "build.gradle.kts"
