include(":DaggerCore")
include(":searchtv")
include(":mainpagetv")
include(":Logging")
include(":ImageLoading")
include(":Navigation")
include(":Remote")
include(":Local")
include(":Domain")
include(":Data")
include(":Favorite")
include(":Search")
include(":MainPage")
include(":app")
rootProject.name = "Movotlin"
rootProject.buildFileName = "build.gradle.kts"
