object BuildModules {
    const val app = ":app"
    const val DaggerCore = ":DaggerCore"
    const val GenreList = ":GenreList"
    const val ViewComponents = ":ViewComponents"
    const val UiBase = ":UiBase"
    const val AndroidBase = ":AndroidBase"
    const val searchtv = ":searchtv"
    const val mainpagetv = ":mainpagetv"
    const val Logging = ":Logging"
    const val Remote = ":Remote"
    const val Local = ":Local"
    const val Domain = ":Domain"
    const val Data = ":Data"
    const val Favorite = ":Favorite"
    const val Search = ":Search"
    const val MainPage = ":MainPage"
    const val tvapp = ":tvapp"

}